version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/PFE/Employee
      - /PFE/Employee/node_modules # Remove this if you have pure JS dependencies
    ports:
      - "8888:8888"
