apiVersion: v1
kind: Service
metadata:
   name: frontend
   labels:
     run: frontend
spec:
   ports:
   - port: 80
     targetPort: 8888
     protocol: TCP
   type: NodePort
   selector:
     run: frontend
