apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend2
spec:
   template:
     metadata:
       labels:
         run: frontend2
     spec:
       containers:
       - name: frontend2
         image: aymen2310/employee
         ports:
         - containerPort: 8888
    
