apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend
spec:
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
     spec:
       containers:
       - name: frontend
         image: aymen2310/employee
         ports:
         - containerPort: 8888
    
