apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: frontend
spec:
   template:
     metadata:
       labels:
         run: frontend
     spec:
       containers:
       - name: frontend
         image: kavisuresh/employee
         ports:
         - containerPort: 8888
